output {
  elasticsearch {
    id => "es-out"
    hosts => ["http://elasticsearch:9200"]
    user => "logstash_internal"
    password => "${LOGSTASH_INTERNAL_PASSWORD}"
    data_stream => false
    index => "logstash-%{+YYYY.MM.dd}"
  }
}
